defaults: &defaults
  schedule:
    step:
      - 了解（指導教授、實驗室、系上）的期望
      - 確定你的研究議題
      - 開發一個方法或方法框架
      - 回顧在這個領域的文獻搜集
      - 建立論文討論會
      - 寫論文提案報告
      - 建立工作計畫 （分析瞭解你的目標，你的情況，你的工作習慣。）
      - 建立論文支持網路關係
      - 開始研究
      - 進行全面的文獻綜合整理
      - 大綱和起草章節
      - 注意視覺化的細節（插圖，表格，數字，圖形等
      - 尋求回饋，審查，重新起草，修改和文字
      - 撰寫論文並使其更加完善
      - 撰寫摘要
      - 口試
      - 完成修改
      - 提交論文

development:
 <<: *defaults
production:
 <<: *defaults
